In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.5


In [3]:
mylist =[1,2,3]

In [4]:
np.array(mylist)

array([1, 2, 3])

array([1, 2, 3])

array([1, 2, 3])

In [3]:
nested_list = [[1,2],[3,4],[5,6]]

In [4]:
print(nested_list)

[[1, 2], [3, 4], [5, 6]]


In [5]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
nest = np.array(nested_list)

In [7]:
print(nest)

[[1 2]
 [3 4]
 [5 6]]
