In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
nparray = np.array(mylist)

array([1, 2, 3])

In [4]:
print(mylist)

[1, 2, 3]


In [5]:
print(nparray)

[1 2 3]


In [6]:
nested_list = [[1,2],[3,4],[5,6]]

In [10]:
# print(nested_list)

[[1, 2], [3, 4], [5, 6]]

In [7]:
nparray_nested = np.array(nested_list)

In [8]:
print(nparray_nested)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
nparr = np.arange(0,10)

In [10]:
print(nparr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
nparr_step = np.arange(0,10,2)

In [12]:
print(nparr_step)

[0 2 4 6 8]


In [16]:
nparr_step_zeroToTen = np.arange(0,11,2)

In [17]:
print(nparr_step_zeroToTen)

[ 0  2  4  6  8 10]
